In [27]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [28]:
dframe = pd.read_csv('streamingserverData.csv',sep=';')


In [29]:
dframe.head(10);

In [30]:
# represent this as delta 
# Then as percentages
dframe.Value;

In [32]:
arr = np.asanyarray(dframe.Value)
arr_debug = arr.copy();




array([ 8.26666667,  7.4       ,  8.26666667, ...,  6.33333333,
        8.        ,  7.53333333])

In [7]:
# code to replace data with their percentages
i = 1;
prec = 0;
i = np.size(arr)-1;
while i>0:
    arr[i] = ((arr[i] - arr[i-1])/arr[i]);  
    i -= 1;
arr[0] = 0;        


In [8]:
arr

array([ 0.        , -0.11711712,  0.10483871, ..., -0.48421053,
        0.20833333, -0.0619469 ])

In [9]:
arr_debug

array([ 8.26666667,  7.4       ,  8.26666667, ...,  6.33333333,
        8.        ,  7.53333333])

In [10]:
arr=arr.T

In [11]:
window=5
arrY = arr[window:]
arrY

array([-0.11471471,  0.07909292, -0.18947368, ..., -0.48421053,
        0.20833333, -0.0619469 ])

In [12]:
a=arr
window=5;
b = [arr[i:i+window] for i in xrange(len(arr)-2)];

In [23]:
myarray = b
myarray;

In [14]:
#repr(dframe.Unix_time[0])[1:-1]

#Result=myarray.T
Result=myarray
#Result=np.arr(myarray.T)
Result;

In [15]:
dframe=pd.DataFrame(Result)
#for i in range(np.size(Result)):
#    dframe[i] = dframe[i][1:-1]

dframe.columns.data

dframe.head()

0         1         2         3         4
0  0.000000 -0.117117  0.104839 -0.252525  0.146552
1 -0.117117  0.104839 -0.252525  0.146552 -0.114715
2  0.104839 -0.252525  0.146552 -0.114715  0.079093
3 -0.252525  0.146552 -0.114715  0.079093 -0.189474
4  0.146552 -0.114715  0.079093 -0.189474  0.194915

In [16]:
min(dframe.count())-1

1496

In [17]:
# debug
dframe = dframe.head(min(dframe.count())-1);
dframe.count()

0    1496
1    1496
2    1496
3    1496
4    1496
dtype: int64

In [18]:
dframeY=pd.DataFrame(arrY)
dframeY.count()

0    1496
dtype: int64

In [19]:
#dframeY=dframeY.T

In [20]:
## Store matrix X and matrix Y
dframe.to_csv('Martrix_X_streamingserver.csv',sep=';',index=False,header=None)
dframeY.to_csv('Martrix_Y_streamingserver.csv',sep=';',index=False,header=None)

In [21]:
dframe.head()

0         1         2         3         4
0  0.000000 -0.117117  0.104839 -0.252525  0.146552
1 -0.117117  0.104839 -0.252525  0.146552 -0.114715
2  0.104839 -0.252525  0.146552 -0.114715  0.079093
3 -0.252525  0.146552 -0.114715  0.079093 -0.189474
4  0.146552 -0.114715  0.079093 -0.189474  0.194915

In [22]:
dframeY.head()

0
0 -0.114715
1  0.079093
2 -0.189474
3  0.194915
4 -0.255319