In [92]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [93]:
dframe = pd.read_csv('serverData.csv',sep=';')


In [94]:
dframe.head(10)

Unix_time     Value
0  1463650587  8.266667
1  1463650602  7.400000
2  1463650617  8.266667
3  1463650632  6.600000
4  1463650647  7.733333
5  1463650663  6.937500
6  1463650678  7.533333
7  1463650693  6.333333
8  1463650708  7.866667
9  1463650723  6.266667

In [95]:
dframe.Value

0        8.266667
1        7.400000
2        8.266667
3        6.600000
4        7.733333
5        6.937500
6        7.533333
7        6.333333
8        7.866667
9        6.266667
10       8.133333
11       6.000000
12       8.933333
13       7.066667
14       9.200000
15       7.533333
16      10.266667
17       6.400000
18       7.866667
19       6.266667
20       8.933333
21       6.533333
22       8.266667
23       7.466667
24       7.866667
25       7.866667
26       9.066667
27       6.400000
28       9.066667
29       7.133333
          ...    
1471     8.133333
1472     6.066667
1473     8.866667
1474     6.266667
1475     8.200000
1476     6.466667
1477     9.266667
1478     6.066667
1479     8.666667
1480     7.333333
1481     8.133333
1482     6.133333
1483     8.133333
1484     7.733333
1485     8.533333
1486     8.600000
1487     8.333333
1488     7.400000
1489    11.466667
1490     8.466667
1491     8.933333
1492    15.000000
1493     8.266667
1494     7.600000
1495     8

In [96]:
arr = np.asanyarray(dframe.Value)

In [97]:
arr=arr.T

In [98]:
window=5
arrY = arr[window:]
arrY

array([ 6.9375    ,  7.53333333,  6.33333333, ...,  6.33333333,
        8.        ,  7.53333333])

In [99]:
a=arr
window=5;
b = [arr[i:i+window] for i in xrange(len(arr)-2)];

In [100]:
myarray = b
myarray

[array([ 8.26666667,  7.4       ,  8.26666667,  6.6       ,  7.73333333]),
 array([ 7.4       ,  8.26666667,  6.6       ,  7.73333333,  6.9375    ]),
 array([ 8.26666667,  6.6       ,  7.73333333,  6.9375    ,  7.53333333]),
 array([ 6.6       ,  7.73333333,  6.9375    ,  7.53333333,  6.33333333]),
 array([ 7.73333333,  6.9375    ,  7.53333333,  6.33333333,  7.86666667]),
 array([ 6.9375    ,  7.53333333,  6.33333333,  7.86666667,  6.26666667]),
 array([ 7.53333333,  6.33333333,  7.86666667,  6.26666667,  8.13333333]),
 array([ 6.33333333,  7.86666667,  6.26666667,  8.13333333,  6.        ]),
 array([ 7.86666667,  6.26666667,  8.13333333,  6.        ,  8.93333333]),
 array([ 6.26666667,  8.13333333,  6.        ,  8.93333333,  7.06666667]),
 array([ 8.13333333,  6.        ,  8.93333333,  7.06666667,  9.2       ]),
 array([ 6.        ,  8.93333333,  7.06666667,  9.2       ,  7.53333333]),
 array([  8.93333333,   7.06666667,   9.2       ,   7.53333333,  10.26666667]),
 array([  7.06666667

In [101]:
#repr(dframe.Unix_time[0])[1:-1]

#Result=myarray.T
Result=myarray
#Result=np.arr(myarray.T)
Result

[array([ 8.26666667,  7.4       ,  8.26666667,  6.6       ,  7.73333333]),
 array([ 7.4       ,  8.26666667,  6.6       ,  7.73333333,  6.9375    ]),
 array([ 8.26666667,  6.6       ,  7.73333333,  6.9375    ,  7.53333333]),
 array([ 6.6       ,  7.73333333,  6.9375    ,  7.53333333,  6.33333333]),
 array([ 7.73333333,  6.9375    ,  7.53333333,  6.33333333,  7.86666667]),
 array([ 6.9375    ,  7.53333333,  6.33333333,  7.86666667,  6.26666667]),
 array([ 7.53333333,  6.33333333,  7.86666667,  6.26666667,  8.13333333]),
 array([ 6.33333333,  7.86666667,  6.26666667,  8.13333333,  6.        ]),
 array([ 7.86666667,  6.26666667,  8.13333333,  6.        ,  8.93333333]),
 array([ 6.26666667,  8.13333333,  6.        ,  8.93333333,  7.06666667]),
 array([ 8.13333333,  6.        ,  8.93333333,  7.06666667,  9.2       ]),
 array([ 6.        ,  8.93333333,  7.06666667,  9.2       ,  7.53333333]),
 array([  8.93333333,   7.06666667,   9.2       ,   7.53333333,  10.26666667]),
 array([  7.06666667

In [102]:
dframe=pd.DataFrame(Result)
#for i in range(np.size(Result)):
#    dframe[i] = dframe[i][1:-1]

dframe.columns.data

dframe.head()

0         1         2         3         4
0  8.266667  7.400000  8.266667  6.600000  7.733333
1  7.400000  8.266667  6.600000  7.733333  6.937500
2  8.266667  6.600000  7.733333  6.937500  7.533333
3  6.600000  7.733333  6.937500  7.533333  6.333333
4  7.733333  6.937500  7.533333  6.333333  7.866667

In [106]:
dframe.to_csv('MartrixX.csv',sep=';',index=False,header=None)

In [107]:
dframe.size

7495

In [105]:
dframe.tail()

0         1         2         3         4
1494  7.600000  8.133333  6.133333  9.400000  6.333333
1495  8.133333  6.133333  9.400000  6.333333  8.000000
1496  6.133333  9.400000  6.333333  8.000000  7.533333
1497  9.400000  6.333333  8.000000  7.533333       NaN
1498  6.333333  8.000000  7.533333       NaN       NaN

In [108]:
dframeY=pd.DataFrame(arrY)

In [109]:
#dframeY=dframeY.T

In [110]:
dframeY.to_csv('MartrixY.csv',sep=';',index=False,header=None)